version: '3.8'

services:
  # 1. PostgreSQL Veritabanı
  vendor-db:
    image: postgres:15-alpine
    container_name: vendor_risk_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: VendorRiskDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - risk-network
      
  # YENİ EKLENEN REDIS SERVİSİ (Hizası vendor-db ve api ile aynı olmalı)
  redis:
    image: redis:7-alpine
    container_name: vendor_risk_redis
    ports:
      - "6379:6379"
    networks:
      - risk-network

  api:
    build:
      context: .
      dockerfile: src/VendorRiskScoring.API/Dockerfile
    container_name: vendor_risk_api
    ports:
      # Bilgisayarının 5188 portunu, container'ın 8080 portuna bağlıyoruz (Swagger'a 5188'den girebilmen için)
      - "5188:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # appsettings.json'daki bağlantı adresini eziyoruz: Host=localhost yerine Host=vendor-db yazıyoruz
      - ConnectionStrings__DefaultConnection=Host=vendor-db;Port=5432;Database=VendorRiskDB;Username=postgres;Password=supersecretpassword
      - ConnectionStrings__RedisConnection=vendor_risk_redis:6379
    volumes:
      # API'nin log yazdığı klasörü host makineye bağlıyoruz, Logstash de buradan okumaya devam edecek
      - ./src/VendorRiskScoring.API/logs:/app/logs
    depends_on:
      - vendor-db
      - logstash
      - redis
    networks:
      - risk-network

  # 2. Elasticsearch (Arama ve Depolama Motoru)
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: vendor_risk_elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - risk-network

  # 3. Logstash (Log İşleme Hattı)
  logstash:
    image: docker.elastic.co/logstash/logstash:8.10.2
    container_name: vendor_risk_logstash
    volumes:
      # Yazdığımız konfigürasyon dosyasını bağlıyoruz
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
      # API projemizin ürettiği günlük log klasörünü Logstash container'ına bağlıyoruz
      - ./src/VendorRiskScoring.API/logs:/usr/share/logstash/logs:ro
    environment:
      - "LS_JAVA_OPTS=-Xms256m -Xmx256m"
    depends_on:
      - elasticsearch
    networks:
      - risk-network

  # 4. Kibana (Görselleştirme Arayüzü)
  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.2
    container_name: vendor_risk_kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - risk-network

volumes:
  postgres_data:
  es_data:

networks:
  risk-network:
    driver: bridge