input {
  file {
    # Logstash container'ı içindeki log klasörünü dinliyoruz
    path => "/usr/share/logstash/logs/*.json"
    start_position => "beginning"
    # Logların kaldığı yeri unutması ve her açılışta baştan okuyabilmesi için (Test kolaylığı sağlar)
    sincedb_path => "/dev/null"
    # Serilog JSON formatında yazdığı için doğrudan json olarak parse ediyoruz
    codec => "json"
  }
}

filter {
  # Burada ileride loglar üzerinde manipülasyon yapmak istersen filtreler uygulayabilirsin.
  # Şimdilik Serilog'un JSON çıktısı zaten çok temiz olduğu için doğrudan geçiyoruz.
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "vendor-risk-logs-%{+YYYY.MM.dd}"
  }
  # Aynı zamanda Logstash konsolunda da log akışını görebilmek için
  stdout { codec => rubydebug }
}